server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    access_log off;
    server_tokens off;

    gzip on;
    gzip_vary on;
    gzip_static on;
    gzip_types application/javascript text/javascript text/css application/json application/wasm model/gltf-binary model/gltf+json image/svg+xml;

    add_header Cache-Control "public, max-age=0, must-revalidate" always;

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    location /textures/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    location / {
        try_files $uri /index.html;
    }
}
